export const localize = {
  common: {
    log_in: "Log In",
    sign_up: "Sign Up",
    cancel: "Cancel",
    save: "Save",
    save_changes: "Save Changes",
    delete: "Delete",
    edit: "Edit",
    view_details: "View Details",
    back: "Back",
    search_placeholder: "Search pets...",
    all_species: "All Species",
    dog: "Dog",
    cat: "Cat",
    logo_alt: "PawPass Logo",
  },
  auth: {
    signup_title: "Create your account with PawPass",
    signup_subtitle: "Give your pet a safer, healthier and happier life",
    signin_title: "Welcome back to PawPass",
    signin_subtitle: "Sign in to continue and keep your pet safe",
    fullname_label: "Full Name",
    email_label: "Email",
    password_label: "Password",
    confirm_password_label: "Confirm Password",
    have_account: "Already have an account?",
    no_account: "Don't have an account?",
  },
  sidebar: {
    dashboard: "Dashboard",
    my_pets: "My Pets",
    health_passport: "Health Passport",
    qr_codes: "QR Codes",
    safety: "Safety",
    lost_pet: "Lost Pets",
    report_found: "Report Found",
    system: "System",
    profile: "Profile",
  },
  pets: {
    title: "My Pets",
    subtitle: "Manage your pets profiles",
    add_pet_btn: "Add New Pet",
    modal_add_title: "Add New Pet",
    modal_edit_title: "Edit Pet",
    modal_details_title: "Pet Details",
    name: "Pet Name",
    species: "Species",
    gender: "Gender",
    dob: "Date of Birth",
    color: "Color",
    weight: "Weight",
    notes: "Notes / About Pet",
    view_qr: "View QR",
    download: "Download",
    report_lost: "Report Lost",
  },
  health: {
    title: "Health Passport",
    subtitle: "Keep track of your pets vaccinations, medications and overall health records.",
    vaccinations: "Vaccinations",
    medications: "Medications",
    add_vaccine: "Add Vaccination",
    add_medication: "Add Medication",
    vaccine_name: "Vaccine Name",
    given_date: "Given Date",
    next_due: "Next Due Date",
    clinic: "Veterinary Clinic",
    vet: "Veterinarian",
    dosage: "Dosage",
    frequency: "Frequency",
    start_date: "Start Date",
    end_date: "End Date",
    status: "Status",
  },
  qr: {
    title: "QR Codes",
    subtitle: "Each pet has a unique QR code. share or download to help get your pet home safely",
    pet_id: "Pet ID",
    share: "Share",
  },
  lost: {
    title: "Lost Pets",
    subtitle: "Browse reported lost pets or report yours missing.",
    report_lost_btn: "Report Lost",
    modal_title: "Report Lost Pet",
    last_seen_loc: "Last Seen Location",
    last_seen_date: "Date and Time Last Seen",
    landmark: "Nearby Landmark",
    description: "Description",
  },
  found: {
    title: "Report Found",
    subtitle: "Pets reported found by PawPass users within 50 km.",
    report_found_btn: "Report Found",
    modal_title: "Report Found Pet",
    found_loc: "Where did you find the pet?",
    found_date: "Date and Time Found",
    submit: "Submit Report",
  },
  profile: {
    title: "Profile",
    subtitle: "Manage your account information",
    personal_info: "Personal Information",
    update_info: "Update your personal details",
  }
};